### PR TITLE
Mobile view cleanup

### PR DESCRIPTION
**Pull request by Frank-Landry**
Added classes to accommodate for mobile view and added mobile only menu icon that will toggle the different routes for viewing.

@iDevelopThings Can you please review? Feel free to leave any and all feedback.

### CODE REVIEW

**Comment by Frank-Landry** [comment]
@iDevelopThings for the added js file, you will want to run npm run dev to have mix pick it up and add it to the public js folder.

**Comment by iDevelopThings** [comment]
Gonna leave notes as I go through on some minor things
Instead of adding new js files that are loaded seperately like with sidemenu in app.blade.php 
You can just require them in app.js - You'll see this in my commit 

https://github.com/Envuso/docs/pull/1/commits/6e3b8276d0a0ce7e13ce0278bb75f0d8e11591ff (don't think this link is correct or wont exist just yet 😅)

**Comment by iDevelopThings** [comment]
@Frank-Landry take a look at these commits, see if you're happy also with the out-come
Ended up changing a few things, but I think it works perfectly now :)

**Review by iDevelopThings — APPROVED** [review]
Thanks Frank :)

**Pull request merged**
